#!/bin/bash
NOT_PRIMARY_FILE=/run/dehydrated/keepalived_not_primary

if [ -d /run/dehydrated ] ; then
  if [ -e "$NOT_PRIMARY_FILE" ] ; then
    rm "$NOT_PRIMARY_FILE"
  fi
fi
systemctl enable dehydrated.timer
